import { randomUUID } from "crypto";
import { and, count, desc, eq, gte, inArray, isNotNull, isNull, like, sql, type SQL } from "drizzle-orm";
import type { ExtensionStatusMap, SkillsStatus } from "lastlight-workflow-engine";
import { nullsToUndefined, tablesOf, type StateClient, type StateTables } from "./client.js";
import { changes, dayBucket, hourBucket, likeEscape, rows, run, sumTrue } from "./dialect.js";
import type { TriggerActorType } from "./user-store.js";
import { normalizeRepoRef, qualifiedRepoSql } from "./repo-ref.js";
import { RESOURCE_USAGE_STOP_REASON } from "../sandbox/resource-usage.js";

export interface ExecutionRecord {
  id: string;
  triggerType: "webhook" | "cron" | "chat" | "api";
  triggerId: string;
  /**
   * Who triggered/acted on this execution (issue #205) — a GitHub login, a
   * Slack display name, or `cli`/`cron`/`admin`. Free-text; joined to `users`
   * on `login` for enrichment. Null on rows written before the column existed.
   */
  triggeredBy?: string;
  /** Coarse actor category for {@link triggeredBy}. */
  triggerActorType?: TriggerActorType;
  skill: string;
  /**
   * GitHub org/user that owns {@link repo}. Its own column since #279, so a
   * ledger row identifies its target without joining the run that owns it —
   * which chat and `build-cycle` rows don't have.
   */
  owner?: string;
  /** BARE repo name (no owner). See `state/repo-ref.ts` for the one rule. */
  repo?: string;
  issueNumber?: number;
  startedAt: string;
  finishedAt?: string;
  success?: boolean;
  error?: string;
  turns?: number;
  durationMs?: number;
  /**
   * Runtime session id (OpenCode `ses_…`) captured from the event stream.
   * Used by the dashboard to look up the session log for a given phase.
   */
  sessionId?: string;
  /** Total USD cost reported by the runtime on the final step. Zero under OAuth/subscription auth. */
  costUsd?: number;
  /** Fresh input tokens (no cache hit). */
  inputTokens?: number;
  /** Tokens that triggered a cache write. */
  cacheCreationInputTokens?: number;
  /** Tokens served from prompt cache. */
  cacheReadInputTokens?: number;
  /** Output tokens generated by the model. */
  outputTokens?: number;
  /** API-side duration (excludes orchestrator overhead). */
  apiDurationMs?: number;
  /** Result subtype, e.g. "success" or "error_max_turns". */
  stopReason?: string;
  /** Sandbox CPU time in seconds (cgroup `cpu.stat`). Absent in-process. */
  cpuSeconds?: number;
  /** Sandbox memory high-water mark in bytes (cgroup `memory.peak`). */
  peakMemoryBytes?: number;
  /** Sandbox memory limit in bytes (cgroup `memory.max`); absent when unlimited. */
  memoryLimitBytes?: number;
  /**
   * Which agentic-pi extensions (file-search / github / web-search) were active
   * for this execution. A real JSON column, so this travels as an OBJECT in
   * both directions and nothing on either side stringifies it.
   */
  extensionStatus?: ExtensionStatusMap;
  /**
   * agentic-pi's skill-loading status for this execution (which skills were
   * discovered/available). A real JSON column, like {@link extensionStatus}.
   * Absent when the run reported no skills.
   */
  skillsStatus?: SkillsStatus;
  /**
   * Workflow run that owns this execution. Scopes dedup: a fresh re-trigger
   * creates a new workflow_run_id, so `shouldRunPhase` won't find matching
   * rows from the prior run and will correctly run the phase again.
   */
  workflowRunId?: string;
}

/**
 * Owns every read/write against the `executions` table — the harness's
 * append-only ledger of agent runs. The dashboard derives phase status from
 * this table (primary source, ahead of the `phase_history` fallback), and the
 * runner's resume path skips already-completed phases via {@link shouldRunPhase}.
 *
 * Carved out of the old `StateDb` god-class (issue #97). Constructed from the
 * single shared Drizzle client so it sits in the same connection scope as the
 * other stores. It is never a transaction participant — no method takes a
 * `dbc` — because nothing else has to move atomically with a ledger append.
 */
/**
 * `executions.repo`, composed into the qualified `owner/repo` a user-facing
 * surface speaks — or NULL when it can't be (issues #169, #279).
 *
 * This used to reach for the owner by joining `workflow_runs` on
 * `workflow_run_id`, because the column was written in two shapes and
 * `executions` had no owner of its own. It now has one (#279), so the join is
 * gone and the answer is on the row.
 *
 * **NULL is the safe answer, and deliberate.** A consumer of this treats null
 * as "no repo, always visible"; returning a bare name instead would produce a
 * value that matches nothing in a qualified allow-list and would therefore
 * HIDE the row. It embeds the schema columns, which render fully qualified
 * (`"executions"."owner"`), so any raw query using it must select from
 * `executions` UNALIASED — the old `e` alias is gone.
 */
const qualifiedRepoOrNull = ({ executions }: StateTables): SQL =>
  qualifiedRepoSql(executions.owner, executions.repo, "null");

/**
 * The columns every BUILDER read that returns an {@link ExecutionRecord}
 * selects.
 *
 * Named explicitly rather than `.select()`-ing the whole row so `output_text`
 * — which is not part of the record and can hold a full LLM response — never
 * rides along on a list read.
 *
 * Its raw-SQL twin is {@link executionColumnsSql}, and {@link deserialize} /
 * {@link mapExecutionRow} are their respective other halves. A new column is
 * added to all four or to none.
 */
const executionColumns = ({ executions }: StateTables) => ({
  id: executions.id,
  triggerType: executions.triggerType,
  triggerId: executions.triggerId,
  triggeredBy: executions.triggeredBy,
  triggerActorType: executions.triggerActorType,
  skill: executions.skill,
  owner: executions.owner,
  repo: executions.repo,
  issueNumber: executions.issueNumber,
  startedAt: executions.startedAt,
  finishedAt: executions.finishedAt,
  success: executions.success,
  error: executions.error,
  turns: executions.turns,
  durationMs: executions.durationMs,
  sessionId: executions.sessionId,
  costUsd: executions.costUsd,
  inputTokens: executions.inputTokens,
  cacheCreationInputTokens: executions.cacheCreationInputTokens,
  cacheReadInputTokens: executions.cacheReadInputTokens,
  outputTokens: executions.outputTokens,
  apiDurationMs: executions.apiDurationMs,
  stopReason: executions.stopReason,
  cpuSeconds: executions.cpuSeconds,
  peakMemoryBytes: executions.peakMemoryBytes,
  memoryLimitBytes: executions.memoryLimitBytes,
  extensionStatus: executions.extensionStatus,
  skillsStatus: executions.skillsStatus,
  workflowRunId: executions.workflowRunId,
});

/** The row shape a builder read of {@link executionColumns} returns. */
type ExecutionRow = Omit<StateTables["executions"]["$inferSelect"], "outputText">;

/**
 * Turn a BUILDER row into an {@link ExecutionRecord}.
 *
 * The builder already did the hard parts — camelCase names, a real boolean for
 * `success`, the two status columns parsed into objects — so this is down to
 * turning nulls into absent optionals and narrowing the two free-text columns
 * the schema types as plain `string`.
 */
function deserialize(row: ExecutionRow): ExecutionRecord {
  const r = nullsToUndefined(row);
  return {
    ...r,
    triggerType: r.triggerType as ExecutionRecord["triggerType"],
    triggerActorType: r.triggerActorType as TriggerActorType | undefined,
  };
}

/**
 * The column list every RAW read that returns an {@link ExecutionRecord}
 * selects — the `sql` twin of {@link executionColumns}.
 *
 * The table is snake_case and the record is camelCase, so an unaliased raw
 * `SELECT *` does not produce an `ExecutionRecord` — it produces a row that
 * *looks* like one for the handful of single-word columns and silently leaves
 * `issueNumber`, `startedAt` and `workflowRunId` `undefined` (issue #285).
 * Three reads did exactly that, and the cast to `ExecutionRecord[]` made the
 * compiler agree.
 *
 * Every alias is DOUBLE-QUOTED: Postgres folds an unquoted `AS triggerId` to
 * `triggerid`, which would resurrect issue #285 the moment the pg leg runs.
 * The columns render fully qualified, so the query must not alias the table.
 */
const executionColumnsSql = ({ executions }: StateTables): SQL => sql`
  ${executions.id}                       AS "id",
  ${executions.triggerType}              AS "triggerType",
  ${executions.triggerId}                AS "triggerId",
  ${executions.triggeredBy}              AS "triggeredBy",
  ${executions.triggerActorType}         AS "triggerActorType",
  ${executions.skill}                    AS "skill",
  ${executions.owner}                    AS "owner",
  ${executions.repo}                     AS "repo",
  ${executions.issueNumber}              AS "issueNumber",
  ${executions.startedAt}                AS "startedAt",
  ${executions.finishedAt}               AS "finishedAt",
  ${executions.success}                  AS "success",
  ${executions.error}                    AS "error",
  ${executions.turns}                    AS "turns",
  ${executions.durationMs}               AS "durationMs",
  ${executions.sessionId}                AS "sessionId",
  ${executions.costUsd}                  AS "costUsd",
  ${executions.inputTokens}              AS "inputTokens",
  ${executions.cacheCreationInputTokens} AS "cacheCreationInputTokens",
  ${executions.cacheReadInputTokens}     AS "cacheReadInputTokens",
  ${executions.outputTokens}             AS "outputTokens",
  ${executions.apiDurationMs}            AS "apiDurationMs",
  ${executions.stopReason}               AS "stopReason",
  ${executions.cpuSeconds}               AS "cpuSeconds",
  ${executions.peakMemoryBytes}          AS "peakMemoryBytes",
  ${executions.memoryLimitBytes}         AS "memoryLimitBytes",
  ${executions.extensionStatus}          AS "extensionStatus",
  ${executions.skillsStatus}             AS "skillsStatus",
  ${executions.workflowRunId}            AS "workflowRunId"
`;

/**
 * Parse one of the two JSON status columns off a RAW row.
 *
 * Raw rows bypass Drizzle's column mapping entirely, so a `{ mode: "json" }`
 * column arrives as the TEXT it is stored as and has to be parsed here.
 * Malformed JSON yields `undefined` rather than throwing — one bad row must
 * not take out the whole executions list.
 */
function parseStatusJson<T>(value: unknown): T | undefined {
  if (value === null || value === undefined) return undefined;
  if (typeof value !== "string") return value as T;
  try {
    return JSON.parse(value) as T;
  } catch {
    return undefined;
  }
}

/**
 * Turn a row selected with {@link executionColumnsSql} into an
 * {@link ExecutionRecord}: NULLs become `undefined` (the record's optional
 * fields), the raw `success` integer becomes a boolean, and the two JSON
 * columns are parsed by hand — none of which a raw query does for you.
 */
function mapExecutionRow(r: Record<string, unknown>): ExecutionRecord {
  const nul = <T>(v: unknown): T | undefined => (v === null || v === undefined ? undefined : (v as T));
  return {
    id: r.id as string,
    triggerType: r.triggerType as ExecutionRecord["triggerType"],
    triggerId: r.triggerId as string,
    triggeredBy: nul<string>(r.triggeredBy),
    triggerActorType: nul<TriggerActorType>(r.triggerActorType),
    skill: r.skill as string,
    owner: nul<string>(r.owner),
    repo: nul<string>(r.repo),
    issueNumber: nul<number>(r.issueNumber),
    startedAt: r.startedAt as string,
    finishedAt: nul<string>(r.finishedAt),
    success: r.success === null || r.success === undefined ? undefined : Boolean(r.success),
    error: nul<string>(r.error),
    turns: nul<number>(r.turns),
    durationMs: nul<number>(r.durationMs),
    sessionId: nul<string>(r.sessionId),
    costUsd: nul<number>(r.costUsd),
    inputTokens: nul<number>(r.inputTokens),
    cacheCreationInputTokens: nul<number>(r.cacheCreationInputTokens),
    cacheReadInputTokens: nul<number>(r.cacheReadInputTokens),
    outputTokens: nul<number>(r.outputTokens),
    apiDurationMs: nul<number>(r.apiDurationMs),
    stopReason: nul<string>(r.stopReason),
    cpuSeconds: nul<number>(r.cpuSeconds),
    peakMemoryBytes: nul<number>(r.peakMemoryBytes),
    memoryLimitBytes: nul<number>(r.memoryLimitBytes),
    extensionStatus: parseStatusJson<ExtensionStatusMap>(r.extensionStatus),
    skillsStatus: parseStatusJson<SkillsStatus>(r.skillsStatus),
    workflowRunId: nul<string>(r.workflowRunId),
  };
}

/** The four ways a finished execution can have turned out (issue #325). */
export interface ExecutionOutcomeCounts {
  succeeded: number;
  skipped: number;
  deferred: number;
  failed: number;
}

/**
 * The outcome classification, as SQL — the ONE definition every aggregation
 * selects (issue #325).
 *
 * `executions.success` is not a health signal and must not be read as one.
 * Two paths write `success = false` deliberately, having failed at nothing:
 *
 *  - **`skipped`** — {@link ExecutionStore.recordSkippedPhase}. Stored
 *    `success = false` so {@link ExecutionStore.shouldRunPhase} re-evaluates the
 *    node on resume. The phase never ran.
 *  - **`error_quota`** — the k8s `ResourceQuota` rejected the pod. The runner
 *    treats it as an ordinary phase failure precisely so the run REQUEUES
 *    (`src/workflows/runner.ts`), and it costs $0 and 0 turns.
 *
 * So the column correctly answers *"may this phase be skipped on resume?"*,
 * where skipped / quota-rejected / crashed are one answer. It was never asked
 * "did something go wrong", and rendering it as though it was painted 251 of a
 * day's 423 executions red on an instance with zero real failures.
 *
 * Held here as a single fragment rather than repeated per query because three
 * aggregations consume it, and three copies would disagree the first time one
 * was edited — the same argument `PrState` makes against six sites each
 * fetching an overlapping subset of the truth.
 *
 * `success IS NULL` (still in flight) matches no bucket on purpose: it counts
 * toward `COUNT(*)` and toward nothing else, so a stacked bar can legitimately
 * be shorter than the execution total. That is why every arm goes through
 * {@link sumTrue} — a `CASE WHEN <predicate>` where NULL falls to the ELSE in
 * both dialects — and why the three that test for failure compare against a
 * BOUND `${false}` rather than a literal `0`, which Postgres rejects outright
 * (`operator does not exist: boolean = integer`).
 *
 * Note `condition_not_met` — a generic-loop `until_bash` check that ran and
 * came back red — is stored `success = true` and therefore lands in
 * `succeeded`. It really executed and really cost tokens; only its per-row
 * rendering is muted (`execMark`, `packages/cli/src/cli-format.ts`).
 *
 * A fan-out's `<phase>_sandbox` row is the one row that is not work at all —
 * see {@link isWork} — so it lands in no outcome.
 */
export const executionOutcomeColumns = (t: StateTables): SQL => {
  const { executions } = t;
  return sql`
        ${sumTrue(sql`${executions.success} AND ${isWork(t)}`)} AS "succeeded",
        ${sumTrue(sql`${executions.success} = ${false} AND ${executions.stopReason} = 'skipped'`)} AS "skipped",
        ${sumTrue(sql`${executions.success} = ${false} AND ${executions.stopReason} = 'error_quota'`)} AS "deferred",
        ${sumTrue(sql`${executions.success} = ${false}
                  AND (${executions.stopReason} IS NULL OR ${executions.stopReason} NOT IN ('skipped', 'error_quota'))`)} AS "failed"`;
};

/**
 * False only for a fan-out's `<phase>_sandbox` row, which records the shared
 * sandbox's CPU / memory and is not an execution of anything. It is kept out of
 * every execution and outcome count — it once rendered as a green, successful
 * run of work even when the fan-out failed — while its `cpu_seconds` still
 * sums, because that CPU was really spent. COALESCE, not `IS DISTINCT FROM`:
 * SQLite has no such operator, and a NULL `stop_reason` is ordinary work.
 */
export const isWork = ({ executions }: StateTables): SQL =>
  sql`COALESCE(${executions.stopReason}, '') <> ${RESOURCE_USAGE_STOP_REASON}`;

/** Zero-fill for a bucket with no executions in it. */
const NO_OUTCOMES: ExecutionOutcomeCounts = { succeeded: 0, skipped: 0, deferred: 0, failed: 0 };

/** One aggregated chat thread — the shape both thread reads return. */
interface ChatThreadSummary {
  triggerId: string;
  agentSessionId: string | null;
  platform: string | null;
  firstStartedAt: string;
  lastActivityAt: string;
  turnCount: number;
  totalCost: number;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  lastAssistantContent: string | null;
  repo: string | null;
}

/** The per-bucket shape {@link ExecutionStore.dailyStats} / `hourlyStats` return. */
type BucketStats = ExecutionOutcomeCounts & {
  date: string;
  executions: number;
  totalTokens: number;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  /**
   * Prompt tokens written to the provider cache. Anthropic reports the uncached
   * prompt prefix here rather than in `inputTokens`; OpenAI-compatible
   * providers have no write bucket and report it as input. Counting it in
   * `totalTokens` keeps the totals comparable across both.
   */
  cacheWriteTokens: number;
  costUsd: number;
  /** Sandbox CPU seconds summed over the bucket's executions. */
  cpuSeconds: number;
  /** The largest single sandbox memory peak in the bucket — a MAX, never a sum. */
  peakMemoryBytes: number;
};

export class ExecutionStore {
  /**
   * Table objects for THIS client's dialect. Every method destructures what it
   * needs off this instead of importing from `schema/sqlite.js` — see
   * `client.ts` → {@link tablesOf} for why the cast alone cannot do it.
   */
  private readonly t: StateTables;

  constructor(private client: StateClient) {
    this.t = tablesOf(client);
  }

  /**
   * Append a started phase to the ledger.
   *
   * Like `createRun`, the (owner, BARE repo) invariant is enforced here rather
   * than asked of callers (issue #279) — the engine writes the pair off
   * `GitSandboxAccess`, the dispatcher off a split `context.repo`, and a
   * qualified value from anywhere else is normalized rather than stored as a
   * second shape.
   */
  async recordStart(
    record: Omit<ExecutionRecord, "finishedAt" | "success" | "error" | "turns" | "durationMs">,
  ): Promise<void> {
    const { executions } = this.t;
    const ref = normalizeRepoRef(record.owner, record.repo);
    await this.client.insert(executions).values({
      id: record.id,
      triggerType: record.triggerType,
      triggerId: record.triggerId,
      skill: record.skill,
      owner: ref.owner ?? null,
      repo: ref.repo ?? null,
      issueNumber: record.issueNumber ?? null,
      startedAt: record.startedAt,
      workflowRunId: record.workflowRunId ?? null,
      triggeredBy: record.triggeredBy ?? null,
      triggerActorType: record.triggerActorType ?? null,
    });
  }

  /**
   * Mid-run update: persist the agent session id as soon as the executor sees
   * the stream-json `system/init` line. Lets the dashboard surface the live
   * session log for an in-flight phase, not just for completed ones.
   */
  async recordSessionId(id: string, sessionId: string): Promise<void> {
    const { executions } = this.t;
    await this.client.update(executions).set({ sessionId }).where(eq(executions.id, id));
  }

  /**
   * Persist the final assistant text for a loop-iteration execution.
   * Used by the runner when a scratch slot would otherwise inline the
   * full LLM output into `workflow_runs.scratch` — the scratch entry
   * stores `lastOutputExecutionId` and resolves the text through
   * `getExecutionOutput` on read.
   */
  async recordOutputText(id: string, output: string): Promise<void> {
    const { executions } = this.t;
    await this.client.update(executions).set({ outputText: output }).where(eq(executions.id, id));
  }

  /** Read the persisted output text for an execution, or null if none. */
  async getExecutionOutput(id: string): Promise<string | null> {
    const { executions } = this.t;
    const [row] = await this.client
      .select({ outputText: executions.outputText })
      .from(executions)
      .where(eq(executions.id, id))
      .limit(1);
    return row?.outputText ?? null;
  }

  /**
   * Most recent finished execution's `output_text` for a phase (`skill`), or
   * null. Used by the reviewer loop on resume to re-derive a completed review's
   * verdict from its persisted output (a dedup-`done` review must not be
   * assumed APPROVED — it may have requested changes).
   */
  async getPhaseOutput(
    skill: string,
    triggerId: string,
    workflowRunId?: string,
  ): Promise<string | null> {
    const { executions } = this.t;
    const [row] = await this.client
      .select({ outputText: executions.outputText })
      .from(executions)
      .where(
        and(
          eq(executions.skill, skill),
          this.scope(triggerId, workflowRunId),
          isNotNull(executions.outputText),
        ),
      )
      .orderBy(desc(executions.finishedAt))
      .limit(1);
    return row?.outputText ?? null;
  }

  async recordFinish(
    id: string,
    result: {
      success: boolean;
      error?: string;
      turns?: number;
      durationMs?: number;
      sessionId?: string;
      costUsd?: number;
      inputTokens?: number;
      cacheCreationInputTokens?: number;
      cacheReadInputTokens?: number;
      outputTokens?: number;
      apiDurationMs?: number;
      stopReason?: string;
      cpuSeconds?: number;
      peakMemoryBytes?: number;
      memoryLimitBytes?: number;
      /** Extensions active this run. An OBJECT — the column is real JSON. */
      extensionStatus?: ExtensionStatusMap;
      /** Skills available this run. An OBJECT — the column is real JSON. */
      skillsStatus?: SkillsStatus;
    },
  ): Promise<void> {
    const { executions } = this.t;
    // The ten optional columns were `COALESCE(?, col)` under raw SQL — "leave
    // what's there when this finish reports nothing". Omitting the key from the
    // SET entirely says the same thing, and says it without a round trip.
    await this.client
      .update(executions)
      .set({
        finishedAt: new Date().toISOString(),
        success: result.success,
        error: result.error ?? null,
        turns: result.turns ?? null,
        durationMs: result.durationMs ?? null,
        ...(result.sessionId !== undefined ? { sessionId: result.sessionId } : {}),
        ...(result.costUsd !== undefined ? { costUsd: result.costUsd } : {}),
        ...(result.inputTokens !== undefined ? { inputTokens: result.inputTokens } : {}),
        ...(result.cacheCreationInputTokens !== undefined
          ? { cacheCreationInputTokens: result.cacheCreationInputTokens }
          : {}),
        ...(result.cacheReadInputTokens !== undefined
          ? { cacheReadInputTokens: result.cacheReadInputTokens }
          : {}),
        ...(result.outputTokens !== undefined ? { outputTokens: result.outputTokens } : {}),
        ...(result.apiDurationMs !== undefined ? { apiDurationMs: result.apiDurationMs } : {}),
        ...(result.stopReason !== undefined ? { stopReason: result.stopReason } : {}),
        ...(result.cpuSeconds !== undefined ? { cpuSeconds: result.cpuSeconds } : {}),
        ...(result.peakMemoryBytes !== undefined ? { peakMemoryBytes: result.peakMemoryBytes } : {}),
        ...(result.memoryLimitBytes !== undefined ? { memoryLimitBytes: result.memoryLimitBytes } : {}),
        ...(result.extensionStatus !== undefined
          ? { extensionStatus: result.extensionStatus }
          : {}),
        ...(result.skillsStatus !== undefined ? { skillsStatus: result.skillsStatus } : {}),
      })
      .where(eq(executions.id, id));
  }

  /**
   * Record a phase that the scheduler skipped because its trigger rule was
   * not satisfied (a failed/skipped upstream cascaded down a chain). The
   * executions ledger is the single source of truth the dashboard derives
   * phase status from, so skips are written here too — as a finished,
   * non-successful row (`success = false`, `stop_reason = 'skipped'`). Because
   * it is not `success = true`, `shouldRunPhase` re-evaluates it on resume (the
   * node will simply be re-skipped if the upstream is still failed).
   */
  async recordSkippedPhase(
    skill: string,
    triggerId: string,
    workflowRunId?: string,
    repo?: string,
    owner?: string,
  ): Promise<void> {
    const { executions } = this.t;
    const now = new Date().toISOString();
    const m = triggerId.match(/#(\d+)$/);
    const issueNumber = m ? Number(m[1]) : null;
    const ref = normalizeRepoRef(owner, repo);
    await this.client.insert(executions).values({
      id: randomUUID(),
      triggerType: "webhook",
      triggerId,
      skill,
      owner: ref.owner ?? null,
      repo: ref.repo ?? null,
      issueNumber,
      startedAt: now,
      finishedAt: now,
      success: false,
      error: "skipped: trigger rule not satisfied",
      stopReason: "skipped",
      workflowRunId: workflowRunId ?? null,
    });
  }

  /**
   * List chat threads aggregated from the executions table.
   *
   * Each row collapses every execution sharing a `trigger_id` (the messaging
   * session id) into one summary so the dashboard's chat-sessions tab can
   * show one card per Slack thread, not one per turn. Joined with
   * `messaging_sessions` for the agent SDK session id (used to resolve to
   * the on-disk jsonl when streaming messages) and with `messaging_messages`
   * for the most recent assistant text (preview snippet).
   */
  async listChatThreads(limit: number): Promise<ChatThreadSummary[]> {
    const { executions, messagingMessages, messagingSessions } = this.t;
    return rows<ChatThreadSummary>(
      this.client,
      sql`
      SELECT
        ${executions.triggerId}             AS "triggerId",
        ${messagingSessions.agentSessionId} AS "agentSessionId",
        ${messagingSessions.platform}       AS "platform",
        -- The thread's repo, for the dashboard's per-repo visibility filter
        -- (issue #169), qualified to owner/repo — a bare name would match
        -- nothing in the allow-list and so HIDE the row. MAX() rather than a
        -- GROUP BY member because it skips NULLs: most chat turns carry no
        -- repo, and one that does should name the whole thread. A thread that
        -- genuinely spans repos picks one — acceptable, since a repo-less
        -- thread stays visible either way.
        MAX(${qualifiedRepoOrNull(this.t)})  AS "repo",
        MIN(${executions.startedAt})        AS "firstStartedAt",
        MAX(COALESCE(${executions.finishedAt}, ${executions.startedAt})) AS "lastActivityAt",
        COUNT(*)                            AS "turnCount",
        SUM(COALESCE(${executions.costUsd}, 0))              AS "totalCost",
        SUM(COALESCE(${executions.inputTokens}, 0))          AS "inputTokens",
        SUM(COALESCE(${executions.outputTokens}, 0))         AS "outputTokens",
        SUM(COALESCE(${executions.cacheReadInputTokens}, 0)) AS "cacheReadTokens",
        (
          SELECT ${messagingMessages.content}
          FROM ${messagingMessages}
          WHERE ${messagingMessages.sessionId} = ${executions.triggerId}
            AND ${messagingMessages.role} = 'assistant'
          ORDER BY ${messagingMessages.timestamp} DESC
          LIMIT 1
        ) AS "lastAssistantContent"
      FROM ${executions}
      LEFT JOIN ${messagingSessions} ON ${messagingSessions.id} = ${executions.triggerId}
      WHERE ${executions.skill} = 'chat'
      -- The two messaging_sessions columns are grouped rather than bare: the
      -- join is on that table's primary key, so each trigger_id still collapses
      -- to exactly one row, but Postgres rejects a bare non-aggregated column.
      GROUP BY ${executions.triggerId}, ${messagingSessions.agentSessionId}, ${messagingSessions.platform}
      ORDER BY "lastActivityAt" DESC
      LIMIT ${limit}
    `,
    );
  }

  /** Look up a single chat thread by its messaging session id (= trigger_id). */
  async getChatThread(triggerId: string): Promise<ChatThreadSummary | null> {
    const { executions, messagingMessages, messagingSessions } = this.t;
    const results = await rows<ChatThreadSummary>(
      this.client,
      sql`
      SELECT
        ${executions.triggerId}             AS "triggerId",
        ${messagingSessions.agentSessionId} AS "agentSessionId",
        ${messagingSessions.platform}       AS "platform",
        -- Same qualification rule as the list above; it read the raw column
        -- here and so disagreed with its own list view for one thread.
        MAX(${qualifiedRepoOrNull(this.t)})  AS "repo",
        MIN(${executions.startedAt})        AS "firstStartedAt",
        MAX(COALESCE(${executions.finishedAt}, ${executions.startedAt})) AS "lastActivityAt",
        COUNT(*)                            AS "turnCount",
        SUM(COALESCE(${executions.costUsd}, 0))              AS "totalCost",
        SUM(COALESCE(${executions.inputTokens}, 0))          AS "inputTokens",
        SUM(COALESCE(${executions.outputTokens}, 0))         AS "outputTokens",
        SUM(COALESCE(${executions.cacheReadInputTokens}, 0)) AS "cacheReadTokens",
        (
          SELECT ${messagingMessages.content}
          FROM ${messagingMessages}
          WHERE ${messagingMessages.sessionId} = ${executions.triggerId}
            AND ${messagingMessages.role} = 'assistant'
          ORDER BY ${messagingMessages.timestamp} DESC
          LIMIT 1
        ) AS "lastAssistantContent"
      FROM ${executions}
      LEFT JOIN ${messagingSessions} ON ${messagingSessions.id} = ${executions.triggerId}
      WHERE ${executions.skill} = 'chat' AND ${executions.triggerId} = ${triggerId}
      GROUP BY ${executions.triggerId}, ${messagingSessions.agentSessionId}, ${messagingSessions.platform}
    `,
    );
    return results[0] ?? null;
  }

  /**
   * The repo a sandbox session ran against, resolved from the `executions`
   * ledger by its `session_id` (issue #169).
   *
   * The fs-backed {@link SessionReader} reads jsonl envelopes that carry no
   * repo of their own, so this is the lookup that lets the dashboard filter the
   * session list by the same allowed-repo set as everything else. Returns null
   * for a session we have no execution row for — those stay visible.
   */
  async repoForSessionId(sessionId: string): Promise<string | null> {
    const { executions } = this.t;
    const [row] = await this.client
      .select({ repo: sql<string | null>`${qualifiedRepoOrNull(this.t)}` })
      .from(executions)
      .where(and(eq(executions.sessionId, sessionId), isNotNull(executions.repo)))
      .orderBy(desc(executions.startedAt))
      .limit(1);
    return row?.repo ?? null;
  }

  /** Check if a skill is currently running for a given trigger */
  async isRunning(skill: string, triggerId: string): Promise<boolean> {
    const { executions } = this.t;
    const [row] = await this.client
      .select({ id: executions.id })
      .from(executions)
      .where(
        and(
          eq(executions.skill, skill),
          eq(executions.triggerId, triggerId),
          isNull(executions.finishedAt),
        ),
      )
      .limit(1);
    return !!row;
  }

  /**
   * Total USD spent by every execution belonging to a run of one of
   * `workflowNames` for this trigger — the cumulative per-PR cost the
   * `fix.maxCostUsd` brake is enforced against (09-state-machine.md → S1).
   *
   * Cost is recorded per PHASE (one `executions` row each) and only ever rolled
   * up per RUN, so there was no way to ask "what has this pull request cost us
   * across every attempt". This is that question, and it is deliberately asked
   * of the same (family, PR) key as `latestForTrigger`: a budget that resets
   * because routing moved from `pr-fix` to `dependabot-ci-fix` is not a budget.
   *
   * Rows with a NULL `cost_usd` (a phase that reported none, or an
   * OAuth/subscription run) contribute 0 — the brake must never be tripped by
   * missing data.
   */
  async costForTriggerWorkflows(triggerId: string, workflowNames: string[]): Promise<number> {
    if (workflowNames.length === 0) return 0;
    const { executions, workflowRuns } = this.t;
    const [row] = await this.client
      .select({ total: sql<number>`COALESCE(SUM(${executions.costUsd}), 0)` })
      .from(executions)
      .innerJoin(workflowRuns, eq(workflowRuns.id, executions.workflowRunId))
      .where(
        and(
          eq(workflowRuns.triggerId, triggerId),
          inArray(workflowRuns.workflowName, workflowNames),
        ),
      );
    return row?.total ?? 0;
  }

  /**
   * Did `workflowRunId` complete phase `phaseName` successfully?
   *
   * Phase ledger rows are keyed `"<workflow>:<phase>"` (the engine's dedup
   * key), so this is a run-scoped `shouldRunPhase` that does not need to know
   * which workflow of a family ran. Used to decide whether a prior fix run
   * actually SPENT an attempt: `diagnose` carries
   * `on_output.requires_marker: DIAGNOSIS_COMPLETE`, so a succeeded row for it
   * is equivalent to the marker having been emitted.
   */
  async phaseSucceededInRun(workflowRunId: string, phaseName: string): Promise<boolean> {
    const { executions } = this.t;
    const [row] = await this.client
      .select({ id: executions.id })
      .from(executions)
      .where(
        and(
          eq(executions.workflowRunId, workflowRunId),
          like(executions.skill, `%:${phaseName}`),
          eq(executions.success, true),
        ),
      )
      .limit(1);
    return !!row;
  }

  /** Check if a skill has already completed successfully for a given trigger */
  async isCompleted(skill: string, triggerId: string): Promise<boolean> {
    const { executions } = this.t;
    const [row] = await this.client
      .select({ id: executions.id })
      .from(executions)
      .where(
        and(
          eq(executions.skill, skill),
          eq(executions.triggerId, triggerId),
          eq(executions.success, true),
        ),
      )
      .limit(1);
    return !!row;
  }

  /**
   * Check if a phase should run: not currently running AND not already
   * succeeded. When `workflowRunId` is provided, scopes the check to that
   * specific run — a fresh re-trigger (new workflow_run_id) will see no
   * matching rows and correctly return "run" even if a prior completed run
   * for the same trigger exists. Omit `workflowRunId` for legacy callers
   * (e.g. chat/status-report dedup) that want the old trigger-wide scope.
   */
  async shouldRunPhase(
    skill: string,
    triggerId: string,
    workflowRunId?: string,
  ): Promise<"run" | "running" | "done"> {
    const { executions } = this.t;
    const scope = this.scope(triggerId, workflowRunId);

    const [running] = await this.client
      .select({ id: executions.id })
      .from(executions)
      .where(and(eq(executions.skill, skill), scope, isNull(executions.finishedAt)))
      .limit(1);
    if (running) return "running";

    const [done] = await this.client
      .select({ id: executions.id })
      .from(executions)
      .where(and(eq(executions.skill, skill), scope, eq(executions.success, true)))
      .limit(1);
    if (done) return "done";

    return "run";
  }

  /** Mark all stale "running" executions for a skill/trigger as failed.
   *  Called when we detect no matching Docker container is alive. */
  async markStaleAsFailed(
    skill: string,
    triggerId: string,
    workflowRunId?: string,
  ): Promise<number> {
    const { executions } = this.t;
    const result = await this.client
      .update(executions)
      .set({
        finishedAt: new Date().toISOString(),
        success: false,
        error: "stale: container no longer running",
      })
      .where(
        and(
          eq(executions.skill, skill),
          this.scope(triggerId, workflowRunId),
          isNull(executions.finishedAt),
        ),
      );
    return changes(result);
  }

  /**
   * Mark every unfinished execution row for a trigger as failed, regardless
   * of skill. Used by the boot-time recovery sweep to clear out phases that
   * were running when the harness crashed/restarted, so the runner's dedup
   * logic doesn't think they're still in flight.
   */
  async markAllStaleForTrigger(triggerId: string, reason: string): Promise<number> {
    const { executions } = this.t;
    const result = await this.client
      .update(executions)
      .set({ finishedAt: new Date().toISOString(), success: false, error: reason })
      .where(and(eq(executions.triggerId, triggerId), isNull(executions.finishedAt)));
    return changes(result);
  }

  /**
   * Mark the most recent execution for a skill/trigger as failed.
   * Used when the agent SDK reported success but the orchestrator decided
   * the business outcome was a failure (e.g. guardrails BLOCKED, reviewer
   * REQUEST_CHANGES). Without this, runPhase would skip the phase on the
   * next run because the DB still says success=true.
   *
   * Raw because of the "newest row wins" correlated subquery. Note the two
   * shapes it needs: the SET column is written UNQUALIFIED (`SET
   * "executions"."success" = …` is not legal SQL in either dialect), and the
   * false is a BOUND param — libsql binds it as 0 and Postgres as a real
   * boolean, where a literal `= 0` would throw `operator does not exist:
   * boolean = integer`.
   */
  async markLatestAsFailed(
    skill: string,
    triggerId: string,
    reason: string,
    workflowRunId?: string,
  ): Promise<number> {
    const { executions } = this.t;
    const scopeSql = workflowRunId
      ? sql`${executions.workflowRunId} = ${workflowRunId}`
      : sql`${executions.triggerId} = ${triggerId}`;
    const result = await run(
      this.client,
      sql`
      UPDATE ${executions}
      SET ${sql.identifier(executions.success.name)} = ${false},
          ${sql.identifier(executions.error.name)} = ${reason}
      WHERE ${executions.id} = (
        SELECT ${executions.id} FROM ${executions}
        WHERE ${executions.skill} = ${skill} AND ${scopeSql}
        ORDER BY ${executions.startedAt} DESC
        LIMIT 1
      )
    `,
    );
    return changes(result);
  }

  /**
   * Why each of `workflowRunIds` failed, in ONE query per 200 ids.
   *
   * The board needs a short reason on a FAILED card, and `workflow_runs` has no
   * error column. Neither of the two obvious alternatives can answer it:
   *
   *  - `workflow_runs.context.error` is OVERWRITTEN on the path that matters.
   *    A guardrails block writes the useful sentence via
   *    `failWorkflow(rule.message)`, and `simple.ts` then calls `finishRun`
   *    again with the failing phase's own `error` — the bare literal
   *    `"BLOCKED"`. (`latestForTriggers` also deliberately does not select
   *    `context`.)
   *  - `phase_history` only records a failure on a THROW: `persistPhase`
   *    hardcodes `success: true`, and a BLOCKED verdict RETURNS a failed
   *    outcome rather than throwing. It would name the last phase that
   *    SUCCEEDED, confidently and wrongly.
   *
   * This ledger is the one place that keeps both the failing phase and the
   * sentence, because `markLatestAsFailed` stamps `rule.message` on the exact
   * row that blocked. Newest failed row per run wins.
   *
   * `success` is compared as a BOUND false — see {@link markLatestAsFailed} for
   * why a literal `= 0` breaks Postgres.
   */
  async failureReasonsForRuns(
    workflowRunIds: string[],
  ): Promise<Map<string, { phase: string; error: string }>> {
    const { executions } = this.t;
    const out = new Map<string, { phase: string; error: string }>();
    const ids = [...new Set(workflowRunIds.filter((id) => !!id))];
    if (ids.length === 0) return out;

    const CHUNK = 200;
    for (let i = 0; i < ids.length; i += CHUNK) {
      const found = await this.client
        .select({
          workflowRunId: executions.workflowRunId,
          skill: executions.skill,
          error: executions.error,
        })
        .from(executions)
        .where(
          and(
            inArray(executions.workflowRunId, ids.slice(i, i + CHUNK)),
            eq(executions.success, false),
            isNotNull(executions.error),
            // ── Artifact rows are not VERDICTS, and must never be shown as
            // why a run failed. Two writers produce `success: false` rows that
            // say nothing about the work:
            //
            //   `recordSkippedPhase` — "skipped: trigger rule not satisfied",
            //   a phase that never ran because its `when:` was false. Left in,
            //   a build killed by something else blames whichever phase was
            //   skipped last, which is both wrong and very convincing.
            //
            //   `markAllStaleForTrigger` — "stale: harness restarted", stamped
            //   on every in-flight row when the process comes back up. That is
            //   a fact about the HARNESS, not about this issue.
            //
            // The `stop_reason` test is NULL-safe deliberately: a bare
            // `<> 'skipped'` would drop every genuine failure, because SQL
            // compares NULL to a literal as NULL rather than as true.
            sql`(${executions.stopReason} IS NULL OR ${executions.stopReason} <> 'skipped')`,
            sql`${executions.error} NOT LIKE 'stale:%'`,
          ),
        )
        .orderBy(desc(executions.startedAt));

      // Newest first, so the first row seen for a run is its latest failure.
      for (const row of found) {
        const runId = row.workflowRunId;
        if (!runId || !row.error || out.has(runId)) continue;
        out.set(runId, { phase: row.skill, error: row.error });
      }
    }
    return out;
  }

  /**
   * The phase each of `workflowRunIds` is RUNNING right now, in ONE query per
   * 200 ids.
   *
   * The board needs this because `workflow_runs.current_phase` answers a
   * subtly different question. `persistPhase` — the only writer — is called on
   * phase COMPLETION (`phase-executor.ts`, after the agent returns and after
   * the approval gate), and it writes the phase that just finished. `createRun`
   * seeds the column with `phases[0]`, so the column happens to be right during
   * the first phase and then lags by exactly one for every phase after it: a
   * run working on `executor` still reads `architect`.
   *
   * Fixing that in the engine would mean writing the column at phase start,
   * which changes what `handleExistingRun` reads to decide a resume point — a
   * shared choke point. So the board answers it from the ledger instead, where
   * an in-flight phase is simply the row that has no `finished_at` yet.
   *
   * Newest unfinished row per run wins.
   */
  async inFlightPhasesForRuns(workflowRunIds: string[]): Promise<Map<string, string>> {
    const { executions } = this.t;
    const out = new Map<string, string>();
    const ids = [...new Set(workflowRunIds.filter(Boolean))];
    if (ids.length === 0) return out;

    const CHUNK = 200;
    for (let i = 0; i < ids.length; i += CHUNK) {
      const found = await this.client
        .select({
          workflowRunId: executions.workflowRunId,
          skill: executions.skill,
        })
        .from(executions)
        .where(
          and(
            inArray(executions.workflowRunId, ids.slice(i, i + CHUNK)),
            isNull(executions.finishedAt),
          ),
        )
        .orderBy(desc(executions.startedAt));

      for (const row of found) {
        const runId = row.workflowRunId;
        if (!runId || out.has(runId)) continue;
        out.set(runId, row.skill);
      }
    }
    return out;
  }

  /** Get recent executions for a skill */
  async recentExecutions(skill: string, limit = 10): Promise<ExecutionRecord[]> {
    const { executions } = this.t;
    const results = await this.client
      .select(executionColumns(this.t))
      .from(executions)
      .where(eq(executions.skill, skill))
      .orderBy(desc(executions.startedAt))
      .limit(limit);
    return results.map(deserialize);
  }

  /**
   * Count consecutive failures for a skill (for cron failure tracking).
   *
   * The compare is `=== false`, not `=== 0`: `success` is a boolean-mode
   * column, so an integer compare is never true and this would report a
   * permanent zero — silently disarming the cron failure alert.
   */
  async consecutiveFailures(skill: string): Promise<number> {
    const { executions } = this.t;
    const results = await this.client
      .select({ success: executions.success })
      .from(executions)
      .where(and(eq(executions.skill, skill), isNotNull(executions.finishedAt)))
      .orderBy(desc(executions.startedAt))
      .limit(10);

    let streak = 0;
    for (const row of results) {
      if (row.success === false) streak++;
      else break;
    }
    return streak;
  }

  /** Get all executions with pagination */
  async allExecutions(limit = 100, offset = 0): Promise<ExecutionRecord[]> {
    const { executions } = this.t;
    const results = await this.client
      .select(executionColumns(this.t))
      .from(executions)
      .orderBy(desc(executions.startedAt))
      .limit(limit)
      .offset(offset);
    return results.map(deserialize);
  }

  /**
   * Free-text search across the `executions` ledger — matches `error`, `skill`,
   * or `repo` against a substring. Used by the `/admin/api/log-search` endpoint
   * and the `lastlight logs search` CLI to find failing/relevant phases without
   * SSHing to the box. Parameterized; the pattern is escaped so user input
   * can't smuggle LIKE wildcards.
   *
   * Raw, because `LIKE … ESCAPE '\'` has no query-builder spelling. Both sides
   * are `lower()`ed rather than leaning on SQLite's case-insensitive LIKE,
   * which Postgres does not share — the case-insensitivity is the feature here,
   * not an accident of the dialect.
   *
   * Matches and returns the QUALIFIED repo, because that is what somebody types
   * (issue #279) — searching `nearform/lastlight` against the bare column found
   * no phase row at all.
   */
  async searchErrors(query: string, limit = 50): Promise<Array<{
    id: string;
    skill: string;
    repo?: string;
    error?: string;
    success?: boolean;
    startedAt: string;
    finishedAt?: string;
    sessionId?: string;
    workflowRunId?: string;
    triggerId: string;
  }>> {
    const { executions } = this.t;
    const pattern = `%${likeEscape(query).toLowerCase()}%`;
    const qualifiedRepo = qualifiedRepoSql(executions.owner, executions.repo, "bare");
    const results = await rows(
      this.client,
      sql`
      SELECT
        ${executions.id}            AS "id",
        ${executions.skill}         AS "skill",
        ${qualifiedRepo}            AS "repo",
        ${executions.error}         AS "error",
        ${executions.success}       AS "success",
        ${executions.startedAt}     AS "startedAt",
        ${executions.finishedAt}    AS "finishedAt",
        ${executions.sessionId}     AS "sessionId",
        ${executions.workflowRunId} AS "workflowRunId",
        ${executions.triggerId}     AS "triggerId"
      FROM ${executions}
      WHERE lower(${executions.error}) LIKE ${pattern} ESCAPE '\\'
         OR lower(${executions.skill}) LIKE ${pattern} ESCAPE '\\'
         OR lower(${qualifiedRepo}) LIKE ${pattern} ESCAPE '\\'
      ORDER BY ${executions.startedAt} DESC
      LIMIT ${limit}
    `,
    );
    return results.map((r) => ({
      id: r.id as string,
      skill: r.skill as string,
      repo: (r.repo as string | null) ?? undefined,
      error: (r.error as string | null) ?? undefined,
      success: r.success === null || r.success === undefined ? undefined : Boolean(r.success),
      startedAt: r.startedAt as string,
      finishedAt: (r.finishedAt as string | null) ?? undefined,
      sessionId: (r.sessionId as string | null) ?? undefined,
      workflowRunId: (r.workflowRunId as string | null) ?? undefined,
      triggerId: r.triggerId as string,
    }));
  }

  /**
   * Get every execution recorded for a workflow run, with camelCase fields
   * ready for the dashboard. Ordered by start time ascending so phases
   * display in the order they ran. Scopes to a specific `workflow_run_id`
   * when provided (preferred — isolates fresh re-triggers from prior runs);
   * falls back to the legacy trigger-wide scope for rows written before the
   * workflow_run_id column existed.
   */
  async getExecutionsForWorkflowRun(
    workflowRunId: string,
    triggerId: string,
    workflowName?: string,
  ): Promise<ExecutionRecord[]> {
    const { executions } = this.t;
    const skillPattern = workflowName ? `${workflowName}:%` : "%:%";
    const results = await rows(
      this.client,
      sql`
      SELECT ${executionColumnsSql(this.t)}
      FROM ${executions}
      WHERE (${executions.workflowRunId} = ${workflowRunId}
             OR (${executions.workflowRunId} IS NULL AND ${executions.triggerId} = ${triggerId}))
        AND ${executions.skill} LIKE ${skillPattern}
      ORDER BY ${executions.startedAt} ASC
    `,
    );

    return results.map(mapExecutionRow);
  }

  /** Get currently running executions (no finished_at) */
  async runningExecutions(): Promise<ExecutionRecord[]> {
    const { executions } = this.t;
    const results = await this.client
      .select(executionColumns(this.t))
      .from(executions)
      .where(isNull(executions.finishedAt))
      .orderBy(desc(executions.startedAt));
    return results.map(deserialize);
  }

  /** Aggregate execution stats */
  async executionStats(): Promise<{
    total_executions: number;
    today_count: number;
    by_skill: Record<string, ExecutionOutcomeCounts & { count: number }>;
    by_trigger: Record<string, number>;
    running: number;
  }> {
    const { executions } = this.t;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const todayIso = today.toISOString();

    // Fan-out `_sandbox` usage rows are not executions of anything — see isWork.
    const work = isWork(this.t);
    const [totalRow] = await this.client.select({ c: count() }).from(executions).where(work);
    const [todayRow] = await this.client
      .select({ c: count() })
      .from(executions)
      .where(and(gte(executions.startedAt, todayIso), work));
    const [runningRow] = await this.client
      .select({ c: count() })
      .from(executions)
      .where(isNull(executions.finishedAt));

    const skillRows = await rows<{ skill: string; count: number } & ExecutionOutcomeCounts>(
      this.client,
      sql`
      SELECT ${executions.skill} AS "skill", COUNT(*) AS "count",
        ${executionOutcomeColumns(this.t)}
      FROM ${executions} WHERE ${work} GROUP BY ${executions.skill}
    `,
    );

    const by_skill: Record<string, ExecutionOutcomeCounts & { count: number }> = {};
    for (const r of skillRows) {
      by_skill[r.skill] = {
        count: r.count,
        succeeded: r.succeeded,
        skipped: r.skipped,
        deferred: r.deferred,
        failed: r.failed,
      };
    }

    const triggerRows = await rows<{ triggerType: string; count: number }>(
      this.client,
      sql`
      SELECT ${executions.triggerType} AS "triggerType", COUNT(*) AS "count"
      FROM ${executions} WHERE ${work} GROUP BY ${executions.triggerType}
    `,
    );

    const by_trigger: Record<string, number> = {};
    for (const r of triggerRows) {
      by_trigger[r.triggerType] = r.count;
    }

    return {
      total_executions: totalRow?.c ?? 0,
      today_count: todayRow?.c ?? 0,
      by_skill,
      by_trigger,
      running: runningRow?.c ?? 0,
    };
  }

  /**
   * What ONE repo's agent work cost since `sinceIso`. The spend line of the
   * weekly digest.
   *
   * `cost_usd` is nullable — rows predating the column, and every `type: bash`
   * phase, carry no cost — so this sums with a COALESCE and reports the phase
   * count separately rather than implying the two are the same denominator.
   */
  async repoCostSince(
    owner: string,
    repo: string,
    sinceIso: string,
  ): Promise<{ costUsd: number; phases: number }> {
    const { executions } = this.t;
    const qualifiedRepo = qualifiedRepoSql(executions.owner, executions.repo, "bare");
    const [row] = await this.client
      .select({
        costUsd: sql<number>`COALESCE(SUM(${executions.costUsd}), 0)`,
        phases: count(),
      })
      .from(executions)
      .where(
        and(
          sql`${qualifiedRepo} = ${`${owner}/${repo}`}`,
          gte(executions.startedAt, sinceIso),
        ),
      );
    return { costUsd: row?.costUsd ?? 0, phases: row?.phases ?? 0 };
  }

  /** Daily aggregated stats for the last N days */
  async dailyStats(days: number): Promise<BucketStats[]> {
    const { executions } = this.t;
    // Build the inclusive UTC date window: [today - (days-1), today].
    // dayBucket() takes the first 10 chars of the ISO-8601 timestamp, so it
    // yields a UTC YYYY-MM-DD string in either dialect and we generate the same
    // format here to align keys.
    const today = new Date();
    const startUtc = new Date(Date.UTC(
      today.getUTCFullYear(),
      today.getUTCMonth(),
      today.getUTCDate() - (days - 1),
    ));

    const dateKeys: string[] = [];
    for (let i = 0; i < days; i++) {
      const d = new Date(startUtc);
      d.setUTCDate(startUtc.getUTCDate() + i);
      dateKeys.push(d.toISOString().slice(0, 10));
    }

    const bucket = dayBucket(executions.startedAt);
    const results = await rows<BucketStats>(
      this.client,
      sql`
      SELECT
        ${bucket} AS "date",
        ${sumTrue(isWork(this.t))} AS "executions",
        ${executionOutcomeColumns(this.t)},
        COALESCE(SUM(${executions.inputTokens}), 0) + COALESCE(SUM(${executions.outputTokens}), 0) + COALESCE(SUM(${executions.cacheReadInputTokens}), 0) + COALESCE(SUM(${executions.cacheCreationInputTokens}), 0) AS "totalTokens",
        COALESCE(SUM(${executions.inputTokens}), 0) AS "inputTokens",
        COALESCE(SUM(${executions.outputTokens}), 0) AS "outputTokens",
        COALESCE(SUM(${executions.cacheReadInputTokens}), 0) AS "cacheReadTokens",
        COALESCE(SUM(${executions.cacheCreationInputTokens}), 0) AS "cacheWriteTokens",
        COALESCE(SUM(${executions.costUsd}), 0) AS "costUsd",
        COALESCE(SUM(${executions.cpuSeconds}), 0) AS "cpuSeconds",
        COALESCE(MAX(${executions.peakMemoryBytes}), 0) AS "peakMemoryBytes"
      FROM ${executions}
      WHERE ${bucket} >= ${dateKeys[0]}
      GROUP BY ${bucket}
    `,
    );

    const byDate = new Map(results.map((r) => [r.date, r]));
    return dateKeys.map((date) => byDate.get(date) ?? {
      date,
      executions: 0,
      ...NO_OUTCOMES,
      totalTokens: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
      costUsd: 0,
      cpuSeconds: 0,
      peakMemoryBytes: 0,
    });
  }

  /** Hourly aggregated stats for the last N hours (UTC). Bucket key is `YYYY-MM-DDTHH`. */
  async hourlyStats(hours: number): Promise<BucketStats[]> {
    const { executions } = this.t;
    const now = new Date();
    const startUtc = new Date(Date.UTC(
      now.getUTCFullYear(),
      now.getUTCMonth(),
      now.getUTCDate(),
      now.getUTCHours() - (hours - 1),
    ));

    const hourKeys: string[] = [];
    for (let i = 0; i < hours; i++) {
      const d = new Date(startUtc);
      d.setUTCHours(startUtc.getUTCHours() + i);
      // YYYY-MM-DDTHH (matches hourBucket(), the first 13 ISO-8601 chars)
      hourKeys.push(d.toISOString().slice(0, 13));
    }

    const bucket = hourBucket(executions.startedAt);
    const results = await rows<BucketStats>(
      this.client,
      sql`
      SELECT
        ${bucket} AS "date",
        ${sumTrue(isWork(this.t))} AS "executions",
        ${executionOutcomeColumns(this.t)},
        COALESCE(SUM(${executions.inputTokens}), 0) + COALESCE(SUM(${executions.outputTokens}), 0) + COALESCE(SUM(${executions.cacheReadInputTokens}), 0) + COALESCE(SUM(${executions.cacheCreationInputTokens}), 0) AS "totalTokens",
        COALESCE(SUM(${executions.inputTokens}), 0) AS "inputTokens",
        COALESCE(SUM(${executions.outputTokens}), 0) AS "outputTokens",
        COALESCE(SUM(${executions.cacheReadInputTokens}), 0) AS "cacheReadTokens",
        COALESCE(SUM(${executions.cacheCreationInputTokens}), 0) AS "cacheWriteTokens",
        COALESCE(SUM(${executions.costUsd}), 0) AS "costUsd",
        COALESCE(SUM(${executions.cpuSeconds}), 0) AS "cpuSeconds",
        COALESCE(MAX(${executions.peakMemoryBytes}), 0) AS "peakMemoryBytes"
      FROM ${executions}
      WHERE ${bucket} >= ${hourKeys[0]}
      GROUP BY ${bucket}
    `,
    );

    const byHour = new Map(results.map((r) => [r.date, r]));
    return hourKeys.map((date) => byHour.get(date) ?? {
      date,
      executions: 0,
      ...NO_OUTCOMES,
      totalTokens: 0,
      inputTokens: 0,
      outputTokens: 0,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
      costUsd: 0,
      cpuSeconds: 0,
      peakMemoryBytes: 0,
    });
  }

  /**
   * The run-vs-trigger scope shared by the five methods that accept an optional
   * `workflowRunId`: prefer the run when the caller knows it, fall back to the
   * trigger-wide scope for legacy callers and pre-`workflow_run_id` rows.
   */
  private scope(triggerId: string, workflowRunId?: string) {
    const { executions } = this.t;
    return workflowRunId
      ? eq(executions.workflowRunId, workflowRunId)
      : eq(executions.triggerId, triggerId);
  }
}
